// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbi

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type InterswitchApiCall struct {
	RequestID    uuid.UUID     `json:"requestID"`
	RemoteIp     string        `json:"remoteIp"`
	Method       string        `json:"method"`
	Url          string        `json:"url"`
	Request      pgtype.JSONB  `json:"request"`
	Response     pgtype.JSONB  `json:"response"`
	ResponseCode sql.NullInt32 `json:"responseCode"`
	InitiatedAt  time.Time     `json:"initiatedAt"`
	CompletedAt  sql.NullTime  `json:"completedAt"`
}
