package api

type ErrorCode string

var (
	ERROR_CODE_NON_EXISTENT_TRANSACTION                               ErrorCode = "90025"
	ERROR_CODE_AN_ERROR_OCCURED                                       ErrorCode = "90096"
	ERROR_CODE_AUTHORIZATION_ERROR                                    ErrorCode = "90063"
	ERROR_CODE_ROUTING_ERROR                                          ErrorCode = "90092"
	ERROR_CODE_EXPIRED_TIN                                            ErrorCode = "90054"
	ERROR_CODE_EXPIRED_PIN                                            ErrorCode = "90054"
	ERROR_CODE_EXPIRED_TOKEN                                          ErrorCode = "90054"
	ERROR_CODE_EXPIRED_OTP                                            ErrorCode = "90054"
	ERROR_CODE_TRANSACTION_APPROVED                                   ErrorCode = "90000"
	ERROR_CODE_DUPLICATE_REQUEST_REFERENCE                            ErrorCode = "90026"
	ERROR_CODE_DUPLICATE_RECORD                                       ErrorCode = "90026"
	ERROR_CODE_REMOTE_SYSTEM_TEMPORARILY_UNAVAILABLE                  ErrorCode = "90091"
	ERROR_CODE_EXCEEDS_CONFIGURED_LIMIT                               ErrorCode = "90098"
	ERROR_CODE_REQUEST_IN_PROGRESS                                    ErrorCode = "90009"
	ERROR_CODE_TRANSACTION_DECLINED_BY_BILLER                         ErrorCode = "90020"
	ERROR_CODE_REJECTED_AS_SUSPECT_DUPLICATE                          ErrorCode = "90094"
	ERROR_CODE_REJECTED_AS_SUSPECT_DUPLICATE_OR_FRAUD                 ErrorCode = "90059"
	ERROR_CODE_ERROR_RESPONSE_FROM_HOST                               ErrorCode = "90006"
	ERROR_CODE_INVALID_AMOUNT                                         ErrorCode = "90013"
	ERROR_CODE_UN_RECOGNIZABLE_CUSTOMER_NUMBER                        ErrorCode = "90052"
	ERROR_CODE_MISSING_PHONE_NUMBER                                   ErrorCode = "900A9"
	ERROR_CODE_UN_ACCEPTABLE_TRANSACTION_FEE                          ErrorCode = "90023"
	ERROR_CODE_INSUFFICIENT_FUNDS                                     ErrorCode = "90051"
	ERROR_CODE_WRONG_PIN_OR_OTP                                       ErrorCode = "90055"
	ERROR_CODE_FORMAT_ERROR                                           ErrorCode = "90030"
	ERROR_CODE_INVALID_PAYMENT_ITEM                                   ErrorCode = "70017"
	ERROR_CODE_INVALID_OR_DUPLICATE_REQUEST_REFERENCE                 ErrorCode = "70018"
	ERROR_CODE_SECURITY_CONFIGURATION_REQUIRED                        ErrorCode = "700A5"
	ERROR_CODE_PASSWORD_CHANGE_REQUIRED                               ErrorCode = "700A6"
	ERROR_CODE_DATA_NOT_FOUND                                         ErrorCode = "70038"
	ERROR_CODE_ACCOUNT_NOT_FOUND                                      ErrorCode = "90052"
	ERROR_CODE_ACCOUNT_NOT_FOUND_2                                    ErrorCode = "70053"
	ERROR_CODE_INCORRECT_FEE_SETUP                                    ErrorCode = "70037"
	ERROR_CODE_TERMINAL_OWNER_NOT_SETUP_OR_CONFIGURED_FOR_THIS_ACTION ErrorCode = "70030"
	ERROR_CODE_UNRECOGNIZED_ISSUER                                    ErrorCode = "70031"
	ERROR_CODE_BILLER_NOT_FOUND                                       ErrorCode = "70010"
	ERROR_CODE_BILLER_NOT_ENABLED_FOR_CHANNEL                         ErrorCode = "70026"
	ERROR_CODE_ISSUER_NOT_ENABLED_FOR_BILLER                          ErrorCode = "70027"
	ERROR_CODE_TERMINAL_OWNER_NOT_ENABLED_FOR_BILLER                  ErrorCode = "70028"
	ERROR_CODE_TERMINAL_OWNER_NOT_ENABLED_FOR_CHANNEL                 ErrorCode = "70029"
	ERROR_CODE_TRANSACTION_NOT_PERMITTED                              ErrorCode = "70058"
	ERROR_CODE_NO_CARD_RECORD                                         ErrorCode = "70056"
	ERROR_CODE_EXPIRED_CARD                                           ErrorCode = "70054"
	ERROR_CODE_TRANSACTION_NOT_PERMITTED_TO_CARDHOLDER                ErrorCode = "70057"
	ERROR_CODE_PIN_TRIES_EXCEEDED                                     ErrorCode = "70038"
	ERROR_CODE_EXCEEDS_WITHDRAWAL_LIMIT                               ErrorCode = "70061"
	ERROR_CODE_RESPONSE_RECEIVED_TOO_LATE                             ErrorCode = "90009"
)
